Saif_PartyMVC/Models/ErrorViewModel.cs
using System;

namespace Saif_PartyMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Saif_PartyMVC/Models/Visitor.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Saif_PartyMVC.Models
{
    public class Visitor
    {
        [Required(ErrorMessage = "Please enter your First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter your Second Name")]
        public string SecondName { get; set; }

        [Required(ErrorMessage = "Please enter your Email Address")]
        [EmailAddress(ErrorMessage = "Email format is not valid")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter your Tel Number")]
        public string Tel { get; set; }

        [Required(ErrorMessage = "Please enter your Age")]
        [Range(18, 60, ErrorMessage = "Age must be between  18 and 60")]
        public int Age { get; set; }

        [Required(ErrorMessage = "Please enter your Address")]
        public string Addtess { get; set; }

        [Required(ErrorMessage = "Please enter your Postal Code")]
        [Range(1000, 1500, ErrorMessage = "Postal code is not valid")]
        public int PostalCode { get; set; }

        [Required(ErrorMessage = "Please enter your City")]
        public string City { get; set; }

        public bool IsFamily { get; set; }
    }
}

Saif_PartyMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Saif_PartyMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Saif_PartyMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Saif_PartyMVC/Controllers/VisitorsController.cs
using Microsoft.AspNetCore.Mvc;
using Saif_PartyMVC.Models;
using System.Collections.Generic;
using System.Linq;
using test.Repository;

namespace Saif_PartyMVC.Controllers
{
    public class VisitorsController : Controller
    {
        private readonly VisitorRepo _repo = new VisitorRepo();

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Visitor visitor)
        {
            _repo.Add(visitor);
            return View();
        }


        [HttpGet]
        public IActionResult Summary()
        {
            TempData["TotalGuests"] = _repo.List.Count;
            TempData["TotalFamilyMembers"] = _repo.List.Count(x => x.IsFamily == true);
            TempData["YoungestGuestAge"] = _repo.List.Count(x => x.Age < x.Age);
            //TempData["YoungestGuestAge"] = _repo.List.OrderByDescending(x => x.Age).LastOrDefault();
            TempData["OldestguestAge"] = _repo.List.Count(x => x.Age > x.Age);

            return View();
        }

        [HttpPost]
        public IActionResult Summary(VisitorRepo visitor)
        {
            int x = (int)TempData.Peek("TotalGuests");
            int y = (int)TempData.Peek("TotalFamilyMembers");
            var z = TempData.Peek("YoungestGuestAge");
            var s = TempData.Peek("OldestguestAge");

            x = _repo.List.Count;
            y = _repo.List.Count(x => x.IsFamily == true);
            z = _repo.List.Count(x => x.Age < x.Age);
            s = _repo.List.Count(x => x.Age > x.Age);

            //z = _repo.List.OrderByDescending(x => x.Age).LastOrDefault();
            //s = _repo.List.OrderByDescending(x => x.Age).FirstOrDefault();

            TempData["TotalGuests"] = x;
            TempData["TotalFamilyMembers"] = y;
            TempData["YoungestGuestAge"] = z;
            TempData["OldestguestAge"] = s;

            return View();
        }
    }
}

Saif_PartyMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Saif_PartyMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Saif_PartyMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Saif_PartyMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visitors" asp-action="Create">Visitors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Saif_PartyMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Saif_PartyMVC/Views/Visitors/Create.cshtml
@model Saif_PartyMVC.Models.Visitor

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Visitor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondName" class="control-label"></label>
                <input asp-for="SecondName" class="form-control" />
                <span asp-validation-for="SecondName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Addtess" class="control-label"></label>
                <input asp-for="Addtess" class="form-control" />
                <span asp-validation-for="Addtess" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsFamily" /> @Html.DisplayNameFor(model => model.IsFamily)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" asp-action="Create" />
            </div>
            <div class="form-group">
                <a asp-action="Summary" class="btn btn-primary">Summary</a>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Saif_PartyMVC/Views/Visitors/Summary.cshtml
@{
    int x = (int)TempData.Peek("TotalGuests");
    int y = (int)TempData.Peek("TotalFamilyMembers");
    int z = (int)TempData.Peek("YoungestGuestAge");
    int s = (int)TempData.Peek("OldestguestAge");
}

@{
    <h1>Overview of the Party Guests</h1>

    <h1>Total Guests : @x</h1>
    <h1>Total Family Members : @y</h1>
    <h1>Youngest guest Age : @z</h1>
    <h1>Oldest guest Age : @s</h1>

}